### ISSUE TITLE
Some inconsistencies adding lots as a non-admin

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#180]
I noticed some inconsistencies when navigating a test auction and adding and editing items with a non-admin account

1. The software wants me to add an address.  This is forced when I edit a lot or add a single lot.  However, when I go to the Auctions list and click the test auction, I can add bult add and edit lots without having an address under my account.  My request is to remove the address requirement for in-person auctions and/or to make any requirement consistent across different ways of adding items

2. When bulk adding lots quantity (a required field) is pre-populated as 1.  When creating individual items, quantity is left blank.  It would be nice to have this pre-populated as a default of qty 1, or to have quantity not be a required field (maybe this could be an auction rule the admin can set?

3. Option to have "description" field as part of bulk adding lots.  (Ideally, I would like an option to have this be an optional printable field on larger labels, but off topic from inconsistencies)

4. Bulk add lots has a field for "buy it now" price, but this field is not available on when creating a single lot with the "create a new lot" button.  (as an admin, I would like the option to remove this)

5. As an admin and as a user, it would be nice to have a prominent button on the top menu that allows me to see my my current auction.  I get a thrown into mix of auctions when I click the top menu.  To get back to my current auction from viewing lots or editing a lot, I need to navigate to the auctions list and reselect my auction.

**Comment by iragm** [comment]
> The software wants me to add an address. This is forced when I edit a lot or add a single lot. However, when I go to the Auctions list and click the test auction, I can add bult add and edit lots without having an address under my account. My request is to remove the address requirement for in-person auctions and/or to make any requirement consistent across different ways of adding items

Address is needed for online auctions, which is what the new single lot page is primarily used for.  I also don't want to require an address for in-person auctions, since it adds friction to the process.

I know the design of this is pretty awkward, but I don't see a clean way to fix it without either making address required for in-person auctions (ugh) or a bunch of confusing dialogs that people won't read.  You are, BTW, the first person who has spotted this, and it's been like that since the bulk add lots page was created.

> When bulk adding lots quantity (a required field) is pre-populated as 1. When creating individual items, quantity is left blank. It would be nice to have this pre-populated as a default of qty 1, or to have quantity not be a required field (maybe this could be an auction rule the admin can set?

This is also by design, and I agree also awkward.  I would be most inclined to "fix" this by removing quantity from in-person auctions altogether.

It is set up like this for online auctions, where having the quantity pre-populated with 1 meant that people kept adding items like "tetras, quantity 1" and they would then be upset when they sold for $2 because bidders assumed there was a single fish.

The bulk add page pre-populates this because for in-person auctions, bidders look in the bag and see that there's more than 1 fish and bid accordingly.

> Option to have "description" field as part of bulk adding lots. (Ideally, I would like an option to have this be an optional printable field on larger labels, but off topic from inconsistencies)

It's difficult to balance the needs of clubs who are running auctions from their phones (yes, actually) and are entering X as the lot name to save typing, and clubs like yours who want extensive information.  For a while, category was on the bulk add lots page and I got complaints that it made things too difficult/confusing.

If you're looking to add extended information about your lots, I'd recommend using the single lot page, that's what it's for.

> Bulk add lots has a field for "buy it now" price, but this field is not available on when creating a single lot with the "create a new lot" button. (as an admin, I would like the option to remove this)

Those fields worked like this at one point, and I removed it.  I did not make a note of why I did that, so I just put them back.

As an admin, you can control the visibility of those fields on both the single lot and bulk add lot pages by setting **Reserve price** and **Buy Now** to **Don't allow**

>As an admin and as a user, it would be nice to have a prominent button on the top menu that allows me to see my my current auction. I get a thrown into mix of auctions when I click the top menu. To get back to my current auction from viewing lots or editing a lot, I need to navigate to the auctions list and reselect my auction.

This has been added. I am not sure I like it, I may move it under the account menu, or just create a button at the top of the auctions list.


Any additional comments and feedback are welcome.

**Comment by iragm** [comment]
> This has been added. I am not sure I like it, I may move it under the account menu, or just create a button at the top of the auctions list.

This has been updated, the last auction used now always displays at the top of the list.  This seems like a good balance of making it easy to find the auction you're (likely) most interested in, without the awkwardness of yet another drop down menu.

**Comment by iragm** [comment]
One more update: there's now an ** Advanced lot adding ** checkbox in your auctions rules.  This controls the description field, quantity, and lot number's visibility in the bulk add lots form.

I think this takes care of the most important issues here and since advanced lot adding is off by default, it keeps things simpler for most people, and makes it just a bit harder for admins to mess with the custom lot number.

Couple notes on the custom lot number (it's unchanged except for its visibility):

* To my knowledge, no one is currently using any system other than the default.
* Users cannot see the lot number field when bulk adding lots, and they can never set or change their own lot numbers
* Changing the lot number after a label has been printed will really trip you up if you don't reprint the label
