### ISSUE TITLE
Possible miscalculation of club commissions

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#234]
At the most recent club auction, we had members charged 15%, 25%, and 35% commission.  The intent was for self-registered items to be charged 15% and items registered by an admin to be charged 25%.  Here are the rules that were set 

The following rules will be automatically enforced by this site:
This is an in-person auction
You can submit lots starting Aug. 27, 2024, 6:30 p.m.
You can submit lots until Sept. 28, 2024, 3:59 p.m.
**For lots you pre-register on auction.fish, you will be charged 15% of the winning price per lot you sell
For lots registered by auction staff on site, you will be charged 25% of the winning price per lot you sell**

To add to the confusion, it seems like the commissions were calculated differently for members and non-members, even though the percentages were set the same.  User error on the admin's part is very possible, and if user-error was the cause, it might be helpful to clarify the commission percentages in the rules, as well as allowing the admin/user to preview the percent that will be charged on the user page or items list.

![Screenshot 2024-10-01 154800](https://github.com/user-attachments/assets/1251b364-59c8-4c70-b7ec-04e8ad43ce49)

**Comment by kmur** [comment]
Adding an example of actual commission charged.  The items were pre-registered by me (an admin) and the commission charged was 35%

![Actual commission charged Screenshot 2024-10-01 155242](https://github.com/user-attachments/assets/3939dd4c-1d27-4d05-8172-9b555ea1a042)

**Comment by iragm** [comment]
This is a bug.  Looks like the pre-registration discount is applied correctly to non-member invoices.  But, for club member invoices, it's added instead of removed.

There are tests for nearly everything in the invoices except this combination, which I somehow missed, and of course that's where the typo was.

Please make a note of the totals of all club member invoices.  I'll put together an update (as soon as I finish writing the tests, probably within the hour) which will have the correct values so you can pay out the difference.

**Comment by kmur** [comment]
Thank you for your prompt reply.  I was able to calculate and pay out the correct amounts by downloading the CSV file.

**Comment by iragm** [comment]
Only one other auction on the site was impacted by this (and fortunately a very small club).  I will email them and let them know.  Looks like not many people are combining the pre-registration discount and club member discounts.
