### ISSUE TITLE
Allow multiple pictures on a lot

### ISSUE THREAD

**Issue by iragm** [iragm/fishauctions#58]
I've gotten the request from a user to allow more than one picture on a lot.  This is something that many (most?) sites support -- ebay, craigslist, kijiji, etc.

The only reason this isn't already implemented is that it adds complexity to the site for users.  In many of the earlier auctions, users were overwhelmed by the amount of information they needed to enter about the lots.  That may be changing as users get used to the site, but it's still tough on new users.  Many users also won't realize they need to swipe to see more pictures.  (Stats say the site is getting around 75% mobile usage and there are very few people under 50, so this is an actual issue).

If this is something you'd like to see, please thumbs up or comment here.

**Comment by bethelite** [comment]
In my humble opinion, since such a high percent are actually using Mobile, I would think that they are accustomed to swiping and using phone apps that do that very thing.  If it does adds some complexity then could the feature be considered later but for now just stick with the one image limitation?  or is it better to plan ahead for the inevitable?  As you adroitly pointed out, many if not most sites support this.

**Comment by iragm** [comment]
This is now available, expect to see lots with multiple pictures in future auctions.

This system may need some tweaking to be a bit more friendly for mobile users, but it's currently easy enough that I don't think people will be too confused by it.  (At least I hope...)

I'll probably publish some stats on the ideal number of pictures once I've collected those data.
